language: cpp

sudo: false

compiler:
  - gcc
  - clang
addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
      - libboost-program-options-dev
      - libssl-dev
      - check
      - scons

script: MEM=$(head -n 1 /proc/meminfo); RAM=(${MEM// / }); MAX_JOBS=$(( ${RAM[1]} / 262144 )); echo Jobs\:\ $MAX_JOBS; ./scripts/build.sh -j $MAX_JOBS
